# General Configurations
FACTOR = 1;
WINDOW_RESOLUTION = "1280x720";
PADY_GLOBAL = 40;
MAIN_BACKGROUND = "#2E2C2F";
MAIN_FONT = "Arial 50";
MAIN_FONT_COLOR = "#ffffff";
PADX_ANSWER_CONTAINER = 40;
MIX_STEPS = 100;
PADX_FUNCTION_BUTTONS = 10;

# Grid Configuration
PADX_GRID = 0;
PADY_GRID = 0;
HEIGHT_GRID = 180;
WIDTH_GRID = 180;
BACKGROUND_GRID = "#000000";
GRID_BUTTON_COLOR = MAIN_FONT_COLOR;
show_number = False;

# Solve Button Configuration
# TENTAR RESOLVER
PADX_SOLVE_BUTTON = (50,0);
PADY_SOLVE_BUTTON = 20;
BACKGROUND_SOLVE_BUTTON = MAIN_BACKGROUND;
FONT_BUTTON = ("Arial", 24);
FONT_BUTTON_COLOR = "#000000";
ACTIVE_FONT_BUTTON_COLOR = "#333333";
WIDTH_SOLVE_BUTTON = 240;
HEIGHT_SOLVE_BUTTON = 130;
TEXTO_SOLVE_BUTTON = "Tentar\nResolver";

# Answer Configuration
PADX_LEFT_ANSWER = PADX_ANSWER_CONTAINER;
PADX_RIGHT_ANSWER = 10;
PADY_ANSWER = 0;
LINE_BREAK_ANSWER = 10;
BACKGROUND_ANSWER = "#DCE0D9";
FONT_ANSWER = "Arial 20";
FONT_ANSWER_COLOR = "#000000";
WIDTH_ANSWER = 600;
HEIGHT_ANSWER = 335;

# Active Number Button
# VER NUMEROS
BACKGROUND_SHOW_NUMBER = MAIN_BACKGROUND;
WIDTH_SHOW_WIDTH = 80;
HEIGHT_SHOW_NUMBER = 80;
FONT_SHOW_BUTTON = ("Arial", 20);
TEXTO_SHOW_NUMBER = "Ver Numeros";
PADX_SHOW_BUTTON = PADX_FUNCTION_BUTTONS;
PADY_SHOW_BUTTON = 0;

# Scramble Button
BACKGROUND_SCRAMBLE = MAIN_BACKGROUND;
WIDTH_SCRAMBLE = 80;
HEIGHT_SCRAMBLE = 80;
FONT_SCRAMBLE = ("Arial", 20);
TEXTO_SCRAMBLE = "Embaralhar";
PADX_SCRAMBLE = PADX_FUNCTION_BUTTONS;
PADY_SCRAMBLE = 0;

# Default Button
BACKGROUND_DEFAULT_BUTTON = MAIN_BACKGROUND;
WIDTH_DEFAULT_BUTTON = 80;
HEIGHT_DEFAULT_BUTTON = 80;
FONT_DEFAULT_BUTTON = ("Arial", 20);
TEXTO_DEFAULT_BUTTON = "Embaralhar";
PADX_DEFAULT_BUTTON = PADX_FUNCTION_BUTTONS;
PADY_DEFAULT_BUTTON = 0;

# Container Answer
BACKGROUND_CONTAINER_ANSWER = MAIN_BACKGROUND;